#!/bin/env sh
echo "downloading images..."
[ -e $(dirname $0)/img/tmux-logo-medium.png ] || (cd $(dirname $0)/img/; wget https://github.com/tmux/tmux/raw/master/logo/tmux-logo-medium.png)
[ -e $(dirname $0)/img/barcode.png ] || (cd $(dirname $0)/img/; qrencode --foreground=000000 --background=ffffff -o barcode.png https://github.com/yazgoo/vmux)
echo "generating conf..."
original_init_vim="$(dirname $0)/../../docker/init.vim"
tmp_init_vim="/tmp/tmp.neovimconf.init.vim"
(cat "$original_init_vim"
echo "
set termguicolors
hi! link StatusLine Normal
hi! link StatusLineNC Normal
set statusline=%{repeat(' ',winwidth('.'))}
set fillchars+=eob: 
set fillchars+=vert: 
set laststatus=0
set nofoldenable
"
) > "$tmp_init_vim"
echo "adjust terminal size:"
while true
do
  l=$(tput lines)
  echo $l == 25
  [ $l -eq 25 ] && break
  read
done
LANG=C vmux -c $(dirname $0)/conf -s NeovimConf new
