#!/bin/env sh
previous_session_name="$1"
clear

if which baus &>/dev/null
then
  baus=baus
else
  baus=""
fi
if which sk &>/dev/null
then
  # lines to be selected from
  lines=$(
  vmux list | grep -v "$previous_session_name" | sed 's/^\*/ /'| $baus --name vmux --action sort --desc --cleanup; vmux list | grep "$previous_session_name"; echo Detach; echo New; 
  list_sessions_names_hook="$HOME/.config/vmux/hooks/list_sessions_names.sh"
  if [ -e "$list_sessions_names_hook" ]
  then
    $list_sessions_names_hook | sed 's/^/New: /'
  fi
  )

  # sk margins
  width=$(echo "$lines" | wc -L)
  height=$(echo "$lines" | wc -l)
  margin_h=$(( (COLUMNS - width - 8)))
  if [ $margin_h -lt 0 ]
  then
    margin_h=0
  fi
  margin_r=$(( margin_h / 5 ))
  margin_l=$(( 4 * margin_h / 5 ))

  margin_v=$(( (LINES - height ) / 2 ))
  if [ $margin_v -lt 0 ]
  then
    margin_v=0
  fi
  margin_v=$(( margin_v + LINES / 5 ))

  # blockish print
  if which blockish >/dev/null 2>&1
  then
    blockish "$(/bin/ls ~/Pictures/vimpapers/*|shuf -n 1)"
  fi

  res=$(echo "$lines" | sk --no-sort --margin=$margin_v,$margin_r,$margin_v,$margin_l --border=rounded --no-clear-start --header="select vmux session" --no-clear)
  if [ "$res" = "Detach" ]
  then
    echo "done"
  elif [ "$res" = "New" ]
  then
    echo "name the session"
    read session_name
    vmux new "$session_name"
  else
    if echo "$res" | grep New: >/dev/null 2>&1
    then
      vmux new "$(echo "$res" | sed 's/New: //')"
    else
      echo "$res" | sed 's/^\*/ /' | $baus --name vmux --action save --value timestamp
      session=$(echo "$res" | sed 's/.*\t//')
      vmux attach "$session"
    fi
  fi
fi
