#!/bin/env sh
if [ $# -gt 0 ]
then
  new_hook="$HOME/.config/vmux/hooks/session_name.sh"
  if [ -e "$new_hook" ]
  then
    . "$new_hook"
  else
    echo "name the session"
    read session_name
  fi
fi

vmux_helper="$(dirname $(dirname $0))/target/release/vmux-helper"

$vmux_helper "new" "$session_name"
