#!/bin/env sh

vmux_helper="$(dirname $(dirname $0))/target/release/vmux-helper"

session_suffix="-vmux-session"

if [ $# -gt 0 ] && [ "$1" = new ]
then
  source $(dirname $0)/__vmux_new
  $vmux_helper "select" "$previous_session_name" "$session_name"
else
  $vmux_helper "$@"
fi
